import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile, rm } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import { execFileSync } from 'node:child_process'
import { WASI } from 'node:wasi'
import { gzipSync } from 'node:zlib'

const root = resolve(import.meta.dirname, '../..')
const cache = join(root, 'node_modules/.cache/web-ide-toolchain')
const sysroot = join(cache, 'sysroot')
const output = join(root, 'public/compiler')
const hash = bytes => createHash('sha256').update(bytes).digest('hex')
const engineVersion = '0.3.15-webide.0.5.0.2'
const compilerDigest = '24fbed474c7b5b4968fd73fc4827440b93fb351c1b6264516130300eff3e7bf5'
const sysrootDigest = '8745c6af23fd841fa507d0c73f6b6b8e8da1b4ec216a6339739a28b38ff7227b'
// Keep these in sync with this exact engine release's src/worker/mod.rs.
const flags = ['-cc1', '-triple', 'wasm32-wasip1', '-Werror', '-disable-free', '-isysroot', '/',
  '-internal-isystem', '/include/c++/v1', '-internal-isystem', '/include',
  '-internal-isystem', '/include/wasm32-wasip1', '-std=c++23', '-fexceptions', '-fcxx-exceptions',
  '-exception-model=wasm', '-target-feature', '+exception-handling', '-mllvm', '-wasm-enable-eh',
  '-mllvm', '-wasm-use-legacy-eh=true']
await mkdir(cache, { recursive: true })
await mkdir(output, { recursive: true })
async function asset(name, digest) {
  const path = join(cache, name)
  let bytes = await readFile(path).catch(() => undefined)
  if (!bytes || hash(bytes) !== digest) {
    const response = await fetch(`https://fabioibanez.github.io/website/${name}`)
    if (!response.ok) throw new Error(`Cannot fetch ${name}: ${response.status}`)
    bytes = Buffer.from(await response.arrayBuffer())
    if (hash(bytes) !== digest) throw new Error(`Unexpected toolchain digest: ${name}`)
    await writeFile(path, bytes)
  }
  return bytes
}
const compiler = await asset('llvm.core.wasm', compilerDigest)
await asset('llvm-resources.tar.gz', sysrootDigest)
await rm(sysroot, { recursive: true, force: true })
await mkdir(sysroot, { recursive: true })
execFileSync('tar', ['-xzf', join(cache, 'llvm-resources.tar.gz'), '-C', sysroot])
const module = await WebAssembly.compile(compiler)
const profiles = []
for (const headers of JSON.parse(await readFile(join(import.meta.dirname, 'profiles.json'), 'utf8'))) {
  const prelude = headers.map(header => `#include <${header}>\n`).join('')
  const headerPath = '/__web_ide_pch.h'
  await writeFile(join(sysroot, headerPath), prelude)
  const args = ['clang', ...flags, '-emit-pch', '-fno-pch-timestamp', '-fvalidate-ast-input-files-content',
    '-x', 'c++-header', '-o', '/headers.pch', headerPath]
  const wasi = new WASI({ version: 'preview1', args, env: {}, preopens: { '/': sysroot }, returnOnExit: true })
  const instance = await WebAssembly.instantiate(module, wasi.getImportObject())
  const code = wasi.start(instance)
  if (code) throw new Error(`PCH build failed (${code}): ${headers}`)
  const bytes = await readFile(join(sysroot, 'headers.pch'))
  const sha256 = hash(bytes)
  const filename = `${headers.join('-')}-${sha256.slice(0, 16)}.pch.bin`
  const compressed = gzipSync(bytes, { level: 9 })
  await writeFile(join(output, filename), compressed)
  profiles.push({ headers, prelude, filename, sha256, bytes: bytes.length, compressedBytes: compressed.length })
  console.log(`${headers.join(', ')}: ${bytes.length} bytes (${compressed.length} compressed)`)
}
const manifest = { engineVersion, compilerDigest, sysrootDigest, flags, profiles }
await writeFile(join(output, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n')
await writeFile(join(root, 'src/nova/generated/pch-profiles.ts'),
  '// Generated by tools/compiler/build-pch.mjs; regenerate after changing the engine or profiles.\n' +
  `export const pchProfiles = ${JSON.stringify(profiles, null, 2)} as const\n`)
